# Node docker image on which our code would run
image: node:10.23.0

#This command is run before all the jobs
before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - mkdir -p /root/.ssh
  - chmod 700 /root/.ssh
  - cp $PRIVATE_KEY /root/.ssh/id_rsa
  - chmod 600 /root/.ssh/id_rsa
  - ssh-add /root/.ssh/id_rsa
  - npm install

stages:
  - test
  - deploy

# lint and test are two different jobs in the same stage.
# This allows us to run these two in parallel and making build faster

# Job 1:
#lint:
#  stage: test
#  script:
#    - npm run lint

# Job 2:
#test:
#  stage: test
#  script:
#    - npm run test

deployToAWS:
  only:
    - master
  stage: deploy
  script:
    - bash deploy/deploy.sh